SELECT PROJECTES.NUM_PROJ, NOM_PROJ, COUNT(DISTINCT CIUTAT_EMPL) AS quantitatdeciutats
FROM PROJECTES LEFT OUTER JOIN EMPLEATS ON (PROJECTES.NUM_PROJ = EMPLEATS.NUM_PROJ)
GROUP BY PROJECTES.NUM_PROJ, NOM_PROJ
ORDER BY PROJECTES.NUM_PROJ ASC
